int A = 25;
int B = 13;
int C = 53;
int D = 29;
int E = 64;
int max = A;
if(B > max) max = B;
if(C > max) max = C;
if(D > max) max = D;
if(E > max) max = E;
Console.Write("max = ");
Console.Write(max);